import tkinter as tk
def saludar():
    nombre = entrada.get()
    edad = entrada.get()
    configure = entrada.get()
    autor = entrada.get()
    etiqueta_resultado.config(text=f"Hola {nombre}, tienes {edad} años.")
ventana = tk.Tk()
ventana.title("Mi primera app gráfica")
ventana.geometry("400x200")
ventana.configure(bg="orange")
etiqueta = tk.Label(ventana, text="Ingresa tu nombre:",bg="light blue")
etiqueta.pack()
entrada = tk.Entry(ventana)
entrada.pack()

etiqueta = tk.Label(ventana, text="Ingresa tu edad:",bg="light green")
etiqueta.pack()
entrada = tk.Entry(ventana)
entrada.pack()

boton = tk.Button(ventana, text="Mostrar saludo", command= saludar)
boton.pack()

etiqueta_resultado = tk.Label(ventana, text="")
etiqueta_resultado.pack()
autor = tk.Label(ventana, text="Fabricio David Rosete Netzahualcoyotl",fg="black", bg="orange")
autor.place(relx=3.0, rely=3.0, x=-260, y=-300, anchor="se")
autor.pack()
ventana.mainloop()
